In [2]:
import cv2 as cv

# Read GrayScale image

In [3]:
#read image 
image = cv.imread("../data/image1.png")

In [4]:
gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
print(gray)

[[163 163 163 ... 172 154 127]
 [163 156 163 ... 168 154 129]
 [163 163 163 ... 168 156 122]
 ...
 [ 40  43  48 ... 107 103  98]
 [ 43  43  50 ... 107 107 107]
 [ 40  43  54 ... 100 104 110]]


In [5]:
print(image.shape)

(512, 512, 3)


In [6]:
print(gray.shape)

(512, 512)


# Read RGB Image

In [7]:
rgb_image= cv.imread("../data/rgb_image.jpg")

In [8]:
rgb_image = cv.cvtColor(image, cv.COLOR_BGR2RGB)
print(rgb_image.shape)
print(rgb_image)

(512, 512, 3)
[[[229 138 118]
  [228 137 129]
  [228 137 129]
  ...
  [234 151 117]
  [220 128 119]
  [194  99  95]]

 [[228 137 129]
  [218 130 129]
  [228 137 129]
  ...
  [230 144 127]
  [222 129 104]
  [205  97  93]]

 [[220 141 124]
  [228 137 129]
  [228 137 129]
  ...
  [234 144 118]
  [223 131 111]
  [199  90  87]]

 ...

 [[ 80  16  60]
  [ 86  18  59]
  [ 89  24  66]
  ...
  [181  74  82]
  [176  70  83]
  [172  64  80]]

 [[ 86  18  59]
  [ 86  18  59]
  [ 96  24  61]
  ...
  [181  74  82]
  [181  74  82]
  [181  74  82]]

 [[ 80  16  60]
  [ 86  18  59]
  [ 96  30  71]
  ...
  [176  66  80]
  [183  69  76]
  [189  75  82]]]


# Split Channels

In [9]:
rgb_image1= cv.imread("../data/colors.jpg")
rgb_image1 = cv.cvtColor(rgb_image1, cv.COLOR_BGR2RGB)
print(rgb_image1.shape)

(540, 720, 3)


In [10]:
(R, G, B) = cv.split(rgb_image1)

# Show the image

Create a window for each channel

In [11]:
cv.namedWindow("Blue", cv.WINDOW_NORMAL)
cv.namedWindow("Green", cv.WINDOW_NORMAL)
cv.namedWindow("Red", cv.WINDOW_NORMAL)

Show the image

In [12]:
cv.imshow("Blue", B)
cv.imshow("Green", G)
cv.imshow("Red", R)

Save the images

In [13]:
cv.imwrite("channel_red.jpg", R)
cv.imwrite("channel_green.jpg", G)
cv.imwrite("channel_blue.jpg", B)

True

In [14]:
rgb_image1= cv.imread("../data/colors.jpg")
(b, g, r) = rgb_image1[0, 0]
print(f"Pixel at (0, 0) - Red: {r}, Green: {g}, Blue: {b}")

Pixel at (0, 0) - Red: 42, Green: 141, Blue: 12


# Drawing 

In [1]:
import numpy as np
import cv2 as cv

In [2]:
canvas= np.zeros((300, 300, 3), dtype="uint8")

In [4]:
green = (0, 255, 0)
cv.line(canvas, (0, 0), (300, 300), green)
cv.imshow("Canvas", canvas)

In [5]:
red = (0, 0, 255)
cv.line(canvas, (300, 0), (0, 300), red)
cv.imshow("Canvas", canvas)

-1

In [6]:
cv.rectangle(canvas, (50, 200), (200, 255), red , 5)
cv.imshow("Canvas", canvas)
cv.waitKey(0)

KeyboardInterrupt: 

In [7]:
blue = (255, 0, 0)
cv.rectangle(canvas, (50, 200), (200, 255), blue , -1)
cv.imshow("Canvas", canvas)
cv.waitKey(0)

-1

### Draw a circle

In [9]:
canvas2= np.zeros((300, 300, 3), dtype="uint8")
#the center of the canvas
(centerX, centerY) = (canvas2.shape[1] // 2, canvas2.shape[0] // 2)
white = (255, 255, 255)
for r in range(0, 150, 25):
    cv.circle(canvas2, (centerX, centerY), r, white, 2)
cv.imshow("Canvas2", canvas2)
cv.waitKey(0)


48

Random centers

In [11]:
for i in range(0,25):
    radius = np.random.randint(5, high=200)
    color = np.random.randint(0, high=200, size=(3,)).tolist()
    pt = np.random.randint(0, high=300, size=(2,)).tolist()
    cv.circle(canvas2, tuple(pt), radius, color, -1)

cv.imshow("Canvas2", canvas2)
cv.waitKey(0)    

-1